#
# Copyright 2012-2019 CNRS-UM LIRMM, CNRS-AIST JRL
#

version: 1.0.{build}
os: Visual Studio 2015
clone_folder: C:/devel-src/Tasks
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
environment:
  CI_OS_NAME: win32
  CI_TOOL: appveyor
  CHOCO_DEPENDENCIES: "doxygen.portable"
  GIT_DEPENDENCIES: "jrl-umi3218/SpaceVecAlg jrl-umi3218/RBDyn jrl-umi3218/eigen-qld jrl-umi3218/sch-core"
# Should be the same as clone_folder
  PROJECT_SOURCE_DIR: C:/devel-src/Tasks
# Do not tinker with the variables below unless you know what you are doing
  SOURCE_FOLDER: C:\devel-src
  CMAKE_INSTALL_PREFIX: C:/devel
  PATH: C:/devel/bin;C:\Libraries\boost_1_59_0\lib64-msvc-14.0;C:\msys64\mingw64\bin;%PATH%
  PKG_CONFIG_PATH: C:/devel/lib/pkgconfig
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib64-msvc-14.0
  MINGW_GFORTRAN: C:\msys64\mingw64\bin\gfortran.exe
build_script:
- ps: >-
    . ./.travis/functions.ps1

    setup_build

    ./.travis/dependencies/eigen-3.2.ps1

    install_dependencies

    build_project
test_script:
- cmd: >-
    cd %PROJECT_SOURCE_DIR%/build

    ctest
